### ISSUE TITLE
Should we update theme for Google Analytics?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-jekyll-theme#19]
Hi @MattReimer 
I want to get Google Analytics going on all of our sites, but want (I think) each site to have its own Analytics ID.  So a series of questions...

# Q1 - Is what I'm doing here kosher?
I tested on the [LTPBR site](http://ltpbr.restoration.usu.edu/) and on the [Capstone class](http://capstone.restoration.usu.edu/) (shown below in video) adding Google Analytics in. I followed [these instructions](https://desiredpersona.com/google-analytics-jekyll/). Here are my code changes: 
- On LTPBR: https://github.com/Riverscapes/PBR/commit/da0ae9e60c13704d9409bb38485118c5fce448ed,  https://github.com/Riverscapes/PBR/commit/0cdff1cbf0d4e1464d0b508fd2393cc7c363de37, and https://github.com/Riverscapes/PBR/commit/182747c189a47d6bc4d0c708a8f24a23645799f3
- On Capstone site: https://github.com/Restoration-USU/WATS-5340-5350/commit/a22ef88c005979263cbad9a17c204f929cbeb5ae,  https://github.com/Restoration-USU/WATS-5340-5350/commit/1bb6f8b121599a47e2bce8b38e1fb6ad93eadeb6, https://github.com/Restoration-USU/WATS-5340-5350/commit/b5c2179eb7919fb3a894c7c09b016209b81c312f

[![](http://img.youtube.com/vi/RBj_8SXZydI/0.jpg)](http://www.youtube.com/watch?v=RBj_8SXZydI "")

# Q2 - Make a Tutorial?
Can we add  [these instructions](https://desiredpersona.com/google-analytics-jekyll/) and above [video](http://www.youtube.com/watch?v=RBj_8SXZydI)  to [Tool Documentation](https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/WebSites/)?

# Q3 - Should we add anything to template site?
Should we just update this repository with the template website so that `_config.yml` file has spot for Google Analytics code and `header.html` has `<head>` code in it, and `analytics.html` is in `includes` folder?

**Comment by philipbaileynar** [comment]
I was also looking at analytics recently. I want to put an id on the buttons where users download our software, but requires some JavaScript in the head and body tags. Ie requires theme changes. Let's discuss.

**Comment by MattReimer** [comment]
OK, so let's start off with the simple stuff. 

Joe, roll back all those changes. Google analytics was built into our themes from the start. In your `config.yml` file there's a line called `google_analytics: UA-XXXXXXXXXXX-X`

Just uncomment that and fill in the UA code and you're good. No Javascript needed.

For Philip's request to log specific actions we will need some javascript but it should be simple and minimal. I can maybe draw up an example of what that looks like and put it in the template theme so you can see how that goes.

**Comment by MattReimer** [comment]
Looks like this is fixed so I'll close it.
