### ISSUE TITLE
Topbar Menu needs to be fixed (broken links)

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-jekyll-theme#21]
![image](https://user-images.githubusercontent.com/9723905/109427668-ae469b80-79b0-11eb-9f8c-8591edc91001.png)

Now that we have over 20 sites using the riverscpes-jekyll-theme, and a lot of traffic, its time we FIX the broken header topbar Menu for all of them. Of the six links, two go to broken links or pages that don't exist and two go to confusing places. Lets fix this. We can't expect people to be excited to pay for our stuff if these basics don't even work.  I know this is my fault as much as anything, but we need to keep our eye on the main points of contacts people have and initial impressions. This is everywhere, and it is sloppy.

## Current Behavior 

| Link   | Current Label  | Current Hyperlink | Behavior / Problem |
|--------|----------------|-------------------|--------------------|
| Link 1 |  Icon ![image](https://user-images.githubusercontent.com/9723905/109427861-81df4f00-79b1-11eb-9b0e-c1cb8f08b7b8.png)               |       [http://riverscapes.xyz/](http://riverscapes.xyz/)            |         Goes to Riverscapes Consortium home page;  Usually an icon of this position on a website goes back to home of that site.          |
| Link 2 | Riverscapes    |          The root of that subdomain site (e.g. BRAT goes to [http://brat.riverscapes.xyz](http://brat.riverscapes.xyz/)         |      Link works, but this is weird label  is "Riverscapes" and it take you back to homepage of this site.         |
| Link 3 | Tools          |       [http://riverscapes.xyz/rc-tools.html](http://riverscapes.xyz/rc-tools.html)            |        Takes you to a useful page of Riverscape Consortium Tools.             |
| Link 4 | Science        |         [https://riverscapes.xyz/rc-science.html](https://riverscapes.xyz/rc-science.html)          |          Takes us to a 404 broken link for page that doesn't exist. Actual [page](https://riverscapes.xyz/Science/science.html) is empty.          |
| Link 5 | Data Warehouse |       [https://riverscapes.xyz/Data_Warehouses/](https://riverscapes.xyz/Data_Warehouses/)            |     Takes user to a populated page explaining what warehouse is, but does not take us to actual [warehouse](http://data.riverscapes.xyz)                |
| Link 6 | Support        |          [https://riverscapes.xyz/support.html](https://riverscapes.xyz/support.html)         |  Takes us to a page that does not exist, nor do we really have plans to make. This is more of a tool-by-tool question.                |

### Should a menu be a menu?
Another odd thing is that most people expect these header type things to be menus (i.e. have menu items and sub-items). We have none. @philipbaileynar and @MattReimer should we?  I can still see populating this with simple stuff (e.g. [About](https://riverscapes.xyz/About/) under Riverscapes.  I guess, what are most users expecting from typical websites. Should we not do that?

## Suggested Changes

Setting aside my menu poke above. Lets at least fix the broken links immediately! Regardless of what's above, lets rethink this to be what we want (can change through time). I think we should simply point people to what we already have. I would suggest (open to suggestions from @MattReimer or @philipbaileynar or @wally-mac):

| Link   | New Label  | Hyperlink | Notes or Why or Questions?|
|--------|----------------|-------------------|--------------------|
| Link 1 |  Icon ![image](https://user-images.githubusercontent.com/9723905/109427861-81df4f00-79b1-11eb-9b0e-c1cb8f08b7b8.png)               |       http://`root`.riverscapes.xyz/ where `root` is the home page of current site (i.e. `{{ site.baseurl }}` instead of http://riverscapes.xyz          |         More consistent with behavior of 90% of websites out there.      |
| Link 2 | Riverscapes Consortium    |          [http://riverscapes.xyz](http://riverscapes.xyz/)         |      This is where we try to "intrigue or invite" a visitor to check out the broader parent Riverscapes Consortium. Potentially have submenu item(s) - (e.g.  [About](https://riverscapes.xyz/About/) that are not embarrassing and populated as opposed to aspirational.       |
| Link 3 | Tools          |      [http://riverscapes.xyz/rc-tools.html](http://riverscapes.xyz/rc-tools.html)            |        Takes you to a useful page of Riverscape Consortium Tools.  This is a good page. It may need exploding later. I am wondering though if maybe we want a `Tools` parent menu that goes nowhere, and then a `RC Tools` that takes us to [that list](https://riverscapes.xyz/Tools/) but another `Production Grade Tools` that takes us to [https://tools.riverscapes.xyz/](https://tools.riverscapes.xyz/)?    Maybe we hold off until we have put more effort into the Production Grade Tools?. Also wondering about  having a menu item of `[Tool Grade](https://riverscapes.xyz/Tools/#tool-grade)`     |
| Link 4 | Data |         [https://data.riverscapes.xyz](https://data.riverscapes.xyz)          |         Let's promote and celebrate what we have. We have a great warehouse. Lets just keep it simple as `Data`.     I'd be happy too with adding menus items of `About RC Data Warehouse` linking to [Warehouse descriptions](https://riverscapes.xyz/Data_Warehouses/), `Getting Data` linking to [here](https://riverscapes.xyz/Data_Warehouses/gettingaround.html), ` and `Riverscapes Projects` linking to [here](https://riverscapes.xyz/Data_Warehouses/gettingaround.html), and if @philipbaileynar  is comfortable a `RC Web Store` pointing to [here](https://north-arrow-research.myshopify.com/collections/all) |
| Link 5 | Maps |       [https://maps.riverscapes.xyz](https://maps.riverscapes.xyz)            |     We don't have any science pages yet, so lets just show off what we have (even if they can't go there with their account access yet)                |
| Link 6 | Empty or Contact? |               |  I'm happy to have just five links for now, and add this later if we get it.    |

Let's NOT loose site of the fact this banner menu is free advertising for the Riverscapes Consortium. Right now, we're doing a poor job capitalizing on that. We have so much great stuff to celebrate, promote and point people towards.

**Comment by MattReimer** [comment]
@joewheaton 100%. I'll make this a priority this week.

**Comment by MattReimer** [comment]
@joewheaton `http://riverscapes.xyz/rc-tools.html` doesn't exist. can I assume you meant `https://riverscapes.xyz/Tools/`

**Comment by MattReimer** [comment]
Ok so this is fixed but....

@joewheaton since we don't have Jekyll 4.0 I can't ripple this change to all our sites. You'll need to correct the `_config.yml` files manually with:

```
  topmenu:
    - title: "Riverscapes Consortium"
      url: http://riverscapes.xyz
    - title: "Tools"
      url: https://riverscapes.xyz/Tools/
    - title: "Data"
      url: https://data.riverscapes.xyz
    - title: "Maps"
      url: https://maps.riverscapes.xyz
```
