### ISSUE TITLE
Should we put this "Wholesale image optimization within GitHub" in our jekyll-theme?

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-jekyll-theme#24]
@philipbaileynar wrote:

> A bot that will optimize all PNGs in a repo. Free for open source repos. Could be useful for our wikis.
> 
> https://github.com/marketplace/imgbot

Seems like it could be good for all our sites and removes [this annoying tinyPNG step](https://riverscapes.xyz/Tools/Technical_Reference/Documentation_Standards/WebSites/Common.html#embedding-an-image)? @MattReimer your thoughts?

**Comment by MattReimer** [comment]
Possible on our public repos. On our private ones we're looking at $30/mo. Seems a little steep for image optimization

**Comment by joewheaton** [comment]
Only useful for ones with websites (all those are public).... am I missing one?

**Comment by MattReimer** [comment]
I've created an issue to try it on the GCD repo. Everything it creates is a commit so it's pretty low risk. 

Once I see how it works and how hard it is to set up we can see if it's worth deploying more broadly.
